# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'vs2017-win2016'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet restore
  displayName: Restore nuget
- task: SonarCloudPrepare@1
  displayName: Prepare Sonar
  inputs:
    SonarCloud: '088aa95d-b2a2-4d2e-907c-ac5b8549dd80'
    organization: 'farlee2121-github'
    projectKey: 'farlee2121_TestingPatterns'
    projectName: 'TestingPatterns'
- task: VSBuild@1
  displayName: 'Build solution **/*.sln'
  inputs:
    solution: '**/*.sln'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactstagingdirectory)\\"'
    configuration: '$(BuildConfiguration)'
- task: SonarSource.sonarcloud.ce096e50-6155-4de8-8800-4221aaeed4a1.SonarCloudAnalyze@1
  displayName: Run Sonar
- task: SonarCloudPublish@1
- task: DotNetCoreCLI@2
  inputs:
    command: test
    projects: '**/Tests.*/*.csproj'
    arguments: '--configuration $(buildConfiguration) --no-build --collect "Code coverage"' 
  displayName: Unit Tests

  
